# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release コピペ補助'
        # Default value if no value is explicitly provided
        default: 'start'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job-combine:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # デフォルト設定
    defaults:
      run: 
        shell: cmd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^

    # Runs a single command using the runners shell
    - name: Output start message
      run: echo "Start combine files"
    - name: Combine src files
      run: call CombineSrcFiles.bat
    - run: exit 0

  job-compression:
    needs: job-combine
    runs-on: windows-latest
    # デフォルト設定
    defaults:
      run: 
        shell: cmd
    steps:
    - name: compression file
      run: echo "Start compression"
    - run: chcp 65001
    - run: makecab /l release コピペ補助.hta コピペ補助.cab
    - run: del コピペ補助.hta
    - run: exit 0
    
