# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release コピペ補助'
        # Default value if no value is explicitly provided
        default: 'start'
        # Input has to be provided for the workflow to run
        required: false

env:
  # Consoleに色を付ける(何が変わったか不明……batch側でも色を出す指定が必要なのかも)
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job-combine:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # デフォルト設定
    defaults:
      run: 
        shell: cmd

    # Remote repositoryから📄を checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^

    # 分割されている source📄 を結合
    - name: Output start message
      run: echo "Start combine files"
    - name: Combine src files
      run: call CombineSrcFiles.bat

    # 作成した HTAファイルを圧縮し、release📂へ
    - name: compression file
      run: echo "Start compression"
    - run: call CompressReleaseFile.bat
    - run: del コピペ補助.hta

    # Localから Ripositoryへ release📄をアップ
    - uses: actions/upload-artifact@v3
      with:
        name: upload-releasezip
        path: release/コピペ補助.zip

# job-create-release:
#   needs: job-combine
    
